# Generated by Django 3.2 on 2023-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=(models.CharField(max_length=200, verbose_name='Название категории'),), unique=True, verbose_name='Адрес категории'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=(models.CharField(max_length=200, verbose_name='Название жанра'),), unique=True, verbose_name='Адрес жанра'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='reviews.Genre', verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'зарегистрированный пользователь'), ('moderator', 'модератор'), ('admin', 'администратор')], default='user', max_length=16),
        ),
    ]
